#!/bin/bash

echo "🌐 Updating Nameservers: Squarespace → Cloudflare"
echo "=============================================="

echo "STEP 1: Get Your Cloudflare Nameservers"
echo "======================================="
echo "In your Cloudflare dashboard, look for something like:"
echo "• Replace your nameservers with:"
echo "• alex.ns.cloudflare.com"
echo "• sara.ns.cloudflare.com"
echo "(Your actual nameservers will be different!)"
echo ""

echo "STEP 2: Update Squarespace Nameservers"
echo "====================================="
echo "1. Login to Squarespace"
echo "2. Go to Settings → Domains"
echo "3. Click on onlibrary.net"
echo "4. Scroll down to find 'Nameservers' section"
echo "5. Change from 'Use Squarespace nameservers' to 'Use custom nameservers'"
echo "6. Enter your Cloudflare nameservers (from Step 1)"
echo "7. Save changes"
echo ""

echo "STEP 3: Configure DNS in Cloudflare"
echo "==================================="
echo "After nameservers are updated:"
echo "1. Go back to Cloudflare dashboard"
echo "2. Click on onlibrary.net → DNS → Records"
echo "3. Add these A records:"
echo "   Type: A | Name: @ | Content: 199.36.158.100"
echo "   Type: A | Name: www | Content: 199.36.158.100"
echo "4. Delete any conflicting records"
echo ""

echo "STEP 4: Wait and Verify"
echo "======================"
echo "• Nameserver changes take 24-48 hours to fully propagate"
echo "• But often work within 30 minutes"
echo "• Run ./check-dns.sh to test"
echo "• Then retry Firebase domain verification"
echo ""

echo "🚨 IMPORTANT: Use YOUR actual Cloudflare nameservers!"
echo "The ones shown above (alex.ns.cloudflare.com) are just examples."
