#!/bin/bash

echo "🔍 Finding Nameservers in Squarespace - Troubleshooting Guide"
echo "=========================================================="

echo "PATH 1: Standard Navigation"
echo "1. squarespace.com → Login"
echo "2. Settings (left sidebar, gear icon ⚙️)"
echo "3. Domains"
echo "4. Click onlibrary.net"
echo "5. Look for one of these:"
echo "   • 'DNS Settings' button"
echo "   • 'Advanced Settings' button"
echo "   • 'Nameservers' section (scroll down)"
echo ""

echo "PATH 2: Alternative Navigation"
echo "1. squarespace.com → Login"
echo "2. Go to main dashboard/home"
echo "3. Look for 'Domains' in top navigation"
echo "4. Click onlibrary.net"
echo "5. Find nameserver settings"
echo ""

echo "WHAT TO LOOK FOR:"
echo "=================="
echo "You need to find text that says:"
echo "• 'Use Squarespace nameservers' (currently selected)"
echo "• 'Use third-party nameservers' (select this one)"
echo "OR"
echo "• 'Use custom nameservers'"
echo "• 'External nameservers'"
echo ""

echo "VISUAL CLUES:"
echo "============="
echo "Look for:"
echo "• Radio buttons (○ ⦿) with nameserver options"
echo "• Text fields to enter custom nameservers"
echo "• Current nameservers showing ns1.squarespace.com"
echo ""

echo "IF YOU CAN'T FIND IT:"
echo "====================="
echo "1. Try searching for 'nameserver' in page (Ctrl+F)"
echo "2. Look for 'DNS' anywhere on the page"
echo "3. Check if there's a 'Connect Domain' option"
echo "4. Look for 'External DNS' or 'Third-party DNS'"
echo ""

echo "SQUARESPACE VERSIONS:"
echo "====================="
echo "• Older Squarespace: Look for 'Connected Domains'"
echo "• Newer Squarespace: Look under Settings → Domains"
echo "• Some accounts: May be under 'Website' → 'Pages' → 'Settings'"
